wine:
	python3 simple_perceptron.py data/wine_train.data data/wine_tune.data data/wine_test.data

titanic:
	python3 simple_perceptron.py data/titanic_train.data data/titanic_tune.data data/titanic_test.data

thoracic:
	python3 simple_perceptron.py data/thoracic_train.data data/thoracic_tune.data data/thoracic_test.data