Instance: Instance.java 
	javac Instance.java 
Dataset: Instance.class Dataset.java
	javac Dataset.java
Lab3: Dataset.class Lab3.java
	javac Lab3.java

main:Lab3.class
	java Lab3 images/trainset images/tuneset images/testset

clean:
	rm *.class